FROM [{BASE_IMAGE}]

RUN yum groupinstall -y "Development Tools"

RUN yum install -y perl-Env
#Needed for OLDER versions of cuda > : |

ENV NVIDIA_VERSION=[{NVIDIA_VERSION}]

SOURCE nvidia.plugin
#SOURCE nvidia-yum-centos7-repo.plugin
#SOURCE nvidia-dnf-centos7-repo.plugin

ENV CUDA_VERSION=[{CUDA_VERSION}]

SOURCE cuda-sample.plugin

CMD bash
