FROM centos:7

RUN yum groupinstall -y "Development Tools"

RUN yum install -y perl-Env
#Needed for OLDER versions of cuda > : |

ENV NVIDIA_VERSION=[{NVIDIA_VERSION}]

SOURCE nvidia.plugin

ENV CUDA_VERSION=[{CUDA_VERSION}]

SOURCE cuda-sample.plugin

CMD bash
